### ISSUE TITLE
Crash while running player without internet connection

### ISSUE THREAD

**Issue by akonior** [nexxtv/nexxPLAY-android#11]
```--------- beginning of crash
08-13 12:46:47.022 9287-10170/com.example.d E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #5
    Process: com.example.d, PID: 9287
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:318)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.substring(int)' on a null object reference
        at tv.nexx.android.player.apiv3.APIManager$2.onReceivedClientToken(APIManager.java:269)
        at tv.nexx.android.player.apiv3.transactions.impls.APICallAsnycTaskInitFlash.doInBackground(APICallAsnycTaskInitFlash.java:84)
        at android.os.AsyncTask$2.call(AsyncTask.java:304)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
        at java.lang.Thread.run(Thread.java:761) ```

**Comment by mfentross** [comment]
I am working on a fix. You can expect it tomorrow.

**Comment by mfentross** [comment]
Thank you for reporting; this has been fixed in v.3.2.0
