### ISSUE TITLE
EceptionInInitializer crash

### ISSUE THREAD

**Issue by NetPumi2** [nexxtv/nexxPLAY-android#15]
Hi guys 
at first, I would like to say we are not sure if this crash comes from nexx. But when we updated nexx we always get this error 
![screen shot 2018-08-21 at 16 40 09](https://user-images.githubusercontent.com/5843275/44461792-86716280-a612-11e8-80b5-c923427ba124.png)
This happens only at first run our app. When we install the app crash because of this bug ... but when we open it again the app works (almost) fine and all videos can play. I just want to ask you if you don't know if it is in nexx or it is on our side somewhere? @mfentross thx

https://stackoverflow.com/questions/51981277/app-crash-at-first-start-after-downloaded-from-google-play-exceptionininitializ

**Comment by mfentross** [comment]
Hil @NetPumi2 , just a small information: we are investigating this and will get back to you asap.

**Comment by mfentross** [comment]
Can you remove anything from your Android Manifest related to DailyMe, please?

`
<receiver android:name="tv.dailyme.android.core.receiver.Autostart">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED" />
            </intent-filter>
        </receiver>
        <receiver
            android:name="tv.dailyme.android.core.receiver.InstallReceiver"
            android:exported="true"
            android:permission="android.permission.INSTALL_PACKAGES">
            <intent-filter>
                <action android:name="com.android.vending.INSTALL_REFERRER" />
            </intent-filter>
        </receiver>

        <service android:name="tv.dailyme.android.util.download.DownloadService" />
        <service android:name="tv.dailyme.android.api.player.audio.AudioService" />
        <service android:name="tv.dailyme.android.core.notification.StopDownloadService" />
        <service android:name="tv.dailyme.android.core.sdcard.ChangeSdCardService" />
`
This block is only needed if you use offline functionality.

**Comment by NetPumi2** [comment]
we don't have any of this part in manifest :(

**Comment by NetPumi2** [comment]
I updated manifest with your lines but still doesn't work this is all errors what we have related to this bug:
this is new only for this release candidate:
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.ViewGroup.setOnTouchListener(android.view.View$OnTouchListener)' on a null object reference
       at de.burda.buntede.video.NexxPlayerActivity.onPlayerError(Unknown Source)
       at tv.nexx.android.player.NexxPlayerAndroidImpl.notifyError(Unknown Source)
       at tv.nexx.android.player.NexxPlayerAndroidImpl.onError(Unknown Source)
       at tv.nexx.android.player.ExoPlayerAdapter.notifyErrorOccurred(Unknown Source)
       at tv.nexx.android.player.ExoPlayerAdapter.onPlayerError(Unknown Source)
       at com.google.android.exoplayer2.ExoPlayerImpl.handleEvent(Unknown Source)
       at com.google.android.exoplayer2.ExoPlayerImpl$1.handleMessage(Unknown Source)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5417)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```
and olders errors: 

`Fatal Exception: java.lang.ExceptionInInitializerError
       at tv.dailyme.android.util.ServerConfig.getUrlRegisterWithoutPhonenr(Unknown Source)
       at tv.dailyme.android.util.UserRegistration.setInstallReferrer(Unknown Source:5)
       at tv.dailyme.android.core.receiver.InstallReceiver.onReceive(Unknown Source:17)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:3392)
       at android.app.ActivityThread.-wrap18(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1780)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6944)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)`

`Fatal Exception: java.lang.RuntimeException: Unable to start receiver tv.dailyme.android.core.receiver.Autostart: java.lang.NullPointerException: Attempt to invoke virtual method 'android.database.sqlite.SQLiteDatabase android.content.Context.openOrCreateDatabase(java.lang.String, int, android.database.sqlite.SQLiteDatabase$CursorFactory, android.database.DatabaseErrorHandler)' on a null object reference
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:3116)
       at android.app.ActivityThread.-wrap18(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1598)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:173)
       at android.app.ActivityThread.main(ActivityThread.java:6459)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:938)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:828)`

`Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setOnTouchListener(android.view.View$OnTouchListener)' on a null object reference
       at de.burda.buntede.video.NexxPlayerActivity.onPlayerError(Unknown Source:36)
       at tv.nexx.android.player.NexxPlayerAndroidImpl.notifyError(Unknown Source:19)
       at tv.nexx.android.player.NexxPlayerAndroidImpl.onError(Unknown Source)
       at tv.nexx.android.player.ExoPlayerAdapter.notifyErrorOccurred(Unknown Source:74)
       at tv.nexx.android.player.ExoPlayerAdapter.onPlayerError(Unknown Source:6)
       at com.google.android.exoplayer2.ExoPlayerImpl.handleEvent(Unknown Source:91)
       at com.google.android.exoplayer2.ExoPlayerImpl$1.handleMessage(Unknown Source:2)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6944)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)`

`Fatal Exception: java.lang.ExceptionInInitializerError
       at tv.dailyme.android.util.ServerConfig.getUrlRegisterWithoutPhonenr(Unknown Source)
       at tv.dailyme.android.util.UserRegistration.setInstallReferrer(Unknown Source)
       at tv.dailyme.android.core.receiver.InstallReceiver.onReceive(Unknown Source)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:3102)
       at android.app.ActivityThread.-wrap18(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1598)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:173)
       at android.app.ActivityThread.main(ActivityThread.java:6459)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:938)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:828)`

**Comment by NetPumi2** [comment]
Hi nexx v 3.2.5 fixed the crash on start THX FOR IT!!! But we have another crash

`Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'int tv.nexx.android.player.control.VideoControllerView$MediaPlayerControl.getDuration()' on a null object reference
       at tv.nexx.android.player.control.VideoControllerView$15.onStopTrackingTouch(Unknown Source)
       at android.widget.SeekBar.onStopTrackingTouch(SeekBar.java:121)
       at android.widget.AbsSeekBar.onTouchEvent(AbsSeekBar.java:604)
       at android.view.View.dispatchTouchEvent(View.java:9300)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
       at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2403)
       at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1737)
       at android.app.Activity.dispatchTouchEvent(Activity.java:2771)
       at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2364)
       at android.view.View.dispatchPointerEvent(View.java:9520)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4230)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4096)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3787)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3844)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5922)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5896)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5857)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6025)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:323)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5417)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`


It happens when we move the video forward... It happened only once (for now)...

**Comment by mfentross** [comment]
Hi @NetPumi2, thank you for your feedback. Could it be that the issue only occurs with the corrupt video file? For now I cannot reproduce the problem.
