### ISSUE TITLE
Version 3 crashes at video play when navigating in progress bar:

### ISSUE THREAD

**Issue by fdobre** [nexxtv/nexxPLAY-android#16]
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.ViewGroup.setOnTouchListener(android.view.View$OnTouchListener)' on a null object reference
       at de.burda.buntede.video.NexxPlayerActivity.onPlayerError(Unknown Source)
       at tv.nexx.android.player.NexxPlayerAndroidImpl.notifyError(Unknown Source)
       at tv.nexx.android.player.NexxPlayerAndroidImpl.onError(Unknown Source)
       at tv.nexx.android.player.ExoPlayerAdapter.notifyErrorOccurred(Unknown Source)
       at tv.nexx.android.player.ExoPlayerAdapter.onPlayerError(Unknown Source)
       at com.google.android.exoplayer2.ExoPlayerImpl.handleEvent(Unknown Source)
       at com.google.android.exoplayer2.ExoPlayerImpl$1.handleMessage(Unknown Source)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5417)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by fdobre** [comment]
![screen shot 2018-08-24 at 12 18 49 pm](https://user-images.githubusercontent.com/3833179/44576760-142a8a80-a798-11e8-8757-b87e7a1fa5d6.png)

**Comment by fdobre** [comment]
`Nexx version 3.2.1

/584/1551164/Y1551164K6CQV6J_720x404_900.mp4?fv=1
`

**Comment by mfentross** [comment]
This is a problem with the video file, not with the player itself. I am closing the ticket.

**Comment by fdobre** [comment]
Is it possible that player display a 'Video is corrupted" instead of crashing?

What can be done to improve the user experience in this case? How is this exception handled in the IOS version?
