### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by NetPumi2** [nexxtv/nexxPLAY-android#17]
Hi again me :D 
we have a nexx v3.2.8
and this issue in crashlytics

```
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
       at tv.nexx.android.player.omnia.VideoUrlBuilderVod.buildFree(Unknown Source:152)
       at tv.nexx.android.player.omnia.VideoUrlBuilderVod.build(Unknown Source:147)
       at tv.nexx.android.player.TransactionGetMedia.makeMediaList(Unknown Source:27)
       at tv.nexx.android.player.TransactionGetMedia$2.onSuccess(Unknown Source:50)
       at tv.nexx.android.player.apiv3.APIManager$8$1.run(Unknown Source:6)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6944)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

and this: 
```Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setOnTouchListener(android.view.View$OnTouchListener)' on a null object reference
       at de.burda.buntede.video.NexxPlayerActivity.onPlayerError(Unknown Source:36)
       at tv.nexx.android.player.NexxPlayerAndroidImpl.notifyError(Unknown Source:19)
       at tv.nexx.android.player.NexxPlayerAndroidImpl.onPlayerLogicError(Unknown Source)
       at tv.nexx.android.player.logic.PlayerLogicStateMachine.firePlayerLogicError(Unknown Source:24)
       at tv.nexx.android.player.logic.PlayerLogicStateMachine.onMediaError(Unknown Source:16)
       at tv.nexx.android.player.logic.PlayerLogic$2.onMediaError(Unknown Source:6)
       at tv.nexx.android.player.logic.MediaManager$3.run(Unknown Source:23)
       at tv.nexx.android.player.TransactionGetMedia$1.onFail(Unknown Source:16)
       at tv.nexx.android.player.apiv3.APIManager$7$2.run(Unknown Source:6)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6944)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)```

**Comment by NetPumi2** [comment]
This is all errors what crashlytics give to us depend on nexx: 
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setOnTouchListener(android.view.View$OnTouchListener)' on a null object reference
       at de.burda.buntede.video.NexxPlayerActivity.onPlayerError(Unknown Source:36)
       at tv.nexx.android.player.NexxPlayerAndroidImpl.notifyError(Unknown Source:19)
       at tv.nexx.android.player.NexxPlayerAndroidImpl.onError(Unknown Source)
       at tv.nexx.android.player.ExoPlayerAdapter.notifyErrorOccurred(Unknown Source:74)
       at tv.nexx.android.player.ExoPlayerAdapter.onPlayerError(Unknown Source:6)
       at com.google.android.exoplayer2.ExoPlayerImpl.handleEvent(Unknown Source:91)
       at com.google.android.exoplayer2.ExoPlayerImpl$1.handleMessage(Unknown Source:2)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6938)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setOnTouchListener(android.view.View$OnTouchListener)' on a null object reference
       at de.burda.buntede.video.NexxPlayerActivity.onPlayerError(Unknown Source)
       at tv.nexx.android.player.NexxPlayerAndroidImpl.notifyError(Unknown Source)
       at tv.nexx.android.player.NexxPlayerAndroidImpl.onError(Unknown Source)
       at tv.nexx.android.player.ExoPlayerAdapter.notifyErrorOccurred(Unknown Source)
       at tv.nexx.android.player.ExoPlayerAdapter.onPlayerError(Unknown Source)
       at com.google.android.exoplayer2.ExoPlayerImpl.handleEvent(Unknown Source)
       at com.google.android.exoplayer2.ExoPlayerImpl$1.handleMessage(Unknown Source)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6776)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)
```
```
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
       at tv.nexx.android.player.omnia.VideoUrlBuilderVod.buildFree(Unknown Source:152)
       at tv.nexx.android.player.omnia.VideoUrlBuilderVod.build(Unknown Source:147)
       at tv.nexx.android.player.TransactionGetMedia.makeMediaList(Unknown Source:27)
       at tv.nexx.android.player.TransactionGetMedia$1.onSuccess(Unknown Source:57)
       at tv.nexx.android.player.apiv3.APIManager$7$1.run(Unknown Source:6)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6938)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

```
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
       at tv.nexx.android.player.omnia.VideoUrlBuilderVod.buildFree(Unknown Source)
       at tv.nexx.android.player.omnia.VideoUrlBuilderVod.build(Unknown Source)
       at tv.nexx.android.player.TransactionGetMedia.makeMediaList(Unknown Source)
       at tv.nexx.android.player.TransactionGetMedia$2.onSuccess(Unknown Source)
       at tv.nexx.android.player.apiv3.APIManager$8$1.run(Unknown Source)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6816)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451)
```
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Exception.getMessage()' on a null object reference
       at tv.nexx.android.player.logic.PlayerLogicStateMachine$30.onMediaError(Unknown Source)
       at tv.nexx.android.player.logic.MediaManager$3.run(Unknown Source)
       at tv.nexx.android.player.TransactionGetMedia$1.onFail(Unknown Source)
       at tv.nexx.android.player.apiv3.APIManager$7$2.run(Unknown Source)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:6134)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
```
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Throwable.getMessage()' on a null object reference
       at tv.nexx.android.player.logic.PlayerLogicStateMachine$30.onMediaError(Unknown Source:4)
       at tv.nexx.android.player.logic.MediaManager$3.run(Unknown Source:23)
       at tv.nexx.android.player.TransactionGetMedia$1.onFail(Unknown Source:16)
       at tv.nexx.android.player.apiv3.APIManager$7$2.run(Unknown Source:6)
       at android.os.Handler.handleCallback(Handler.java:808)
       at android.os.Handler.dispatchMessage(Handler.java:101)
       at android.os.Looper.loop(Looper.java:166)
       at android.app.ActivityThread.main(ActivityThread.java:7425)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
```

**Comment by NetPumi2** [comment]
we can close this because when i fix `.video.NexxPlayerActivity.onPlayerError(Unknown Source:36)`
otheres issues disapear
