### ISSUE TITLE
java.lang.Exception.getMessage()

### ISSUE THREAD

**Issue by NetPumi2** [nexxtv/nexxPLAY-android#19]
Hi me again :D 
we fixed all issues depend on nexx. But now fabric.io shows new (very rarely but still it is an issue):
we use version 3.2.8

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Throwable.getMessage()' on a null object reference
       at tv.nexx.android.player.logic.PlayerLogicStateMachine$30.onMediaError(Unknown Source)
       at tv.nexx.android.player.logic.MediaManager$3.run(Unknown Source)
       at tv.nexx.android.player.TransactionGetMedia$1.onFail(Unknown Source)
       at tv.nexx.android.player.apiv3.APIManager$7$2.run(Unknown Source)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6776)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)
```
and
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Exception.getMessage()' on a null object reference
       at tv.nexx.android.player.logic.PlayerLogicStateMachine$30.onMediaError(Unknown Source:4)
       at tv.nexx.android.player.logic.MediaManager$3.run(Unknown Source:23)
       at tv.nexx.android.player.TransactionGetMedia$1.onFail(Unknown Source:16)
       at tv.nexx.android.player.apiv3.APIManager$7$2.run(Unknown Source:6)
       at android.os.Handler.handleCallback(Handler.java:809)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:166)
       at android.app.ActivityThread.main(ActivityThread.java:7377)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:963)
```

**Comment by boredom2** [comment]
Hi @NetPumi2 - Malte is sick this week but will probably will be back Beginning of next Week. Thats why he didnt answer yet - but he will :)

**Comment by mfentross** [comment]
Hi @NetPumi2 , 

thank you for reporting. This has been fixed in v. 3.2.20
