### ISSUE TITLE
Crash on swapToPos

### ISSUE THREAD

**Issue by stigi** [nexxtv/nexxPLAY-android#20]
Hi 👋,

In an attempt to work around #18 I tried calling `swapToPos` to jump to a position within a video that's currently playing.

This triggers an exception with the following logs though:

```
09-14 11:41:23.172 14615-14615/net.funk.tv.debug D/NEXX: Calling swapToPos(param=20
09-14 11:41:23.172 14615-14615/net.funk.tv.debug I/NEXX: SwapToPos 20
09-14 11:41:23.173 14615-14615/net.funk.tv.debug E/NEXX: index out of bounds
09-14 11:41:30.094 2008-2535/com.google.android.gms.persistent W/ctxmgr: [AclManager]No 2 for (accnt=account#-517948760#, com.google.android.gms(10011):IndoorOutdoorProducer, vrsn=12874000, 0, 3pPkg = null ,  3pMdlId = null ,  pid = 2008). Was: 3 for 57, account#-517948760#
09-14 11:41:33.110 14615-14615/net.funk.tv.debug D/AndroidRuntime: Shutting down VM
    
    
    --------- beginning of crash
09-14 11:41:33.112 14615-14615/net.funk.tv.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: net.funk.tv.debug, PID: 14615
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean tv.nexx.android.player.Media.isPay()' on a null object reference
        at tv.nexx.android.player.logic.MediaManager.checkPayStatusAsync(MediaManager.java:256)
        at tv.nexx.android.player.logic.PlayerLogicStateMachine.checkPayStatus(PlayerLogicStateMachine.java:1114)
        at tv.nexx.android.player.logic.PlayerLogicStateMachine.SwapToPos(PlayerLogicStateMachine.java:1434)
        at tv.nexx.android.player.logic.PlayerLogic.swapToPos(PlayerLogic.java:386)
        at tv.nexx.android.player.NexxPlayerAndroidImpl.swapToPos(NexxPlayerAndroidImpl.java:312)
        at net.funk.tv.player.PlayerActivity.onPlayerEvent(PlayerActivity.kt:108)
        at tv.nexx.android.player.NexxPlayerAndroidImpl.onPlayerEvent(NexxPlayerAndroidImpl.java:510)
        at tv.nexx.android.player.logic.PlayerLogicStateMachine.firePlayerEvent(PlayerLogicStateMachine.java:1919)
        at tv.nexx.android.player.logic.PlayerLogicStateMachine.onTick(PlayerLogicStateMachine.java:1663)
        at tv.nexx.android.player.logic.PlayerLogic.onTick(PlayerLogic.java:282)
        at tv.nexx.android.player.logic.PlayerLogic$MessageHandler.handleMessage(PlayerLogic.java:592)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
    
    
    --------- beginning of system
09-14 11:41:33.116 1620-2146/system_process W/ActivityManager:   Force finishing activity net.funk.tv.debug/net.funk.tv.player.PlayerActivity
```

 I tried it with videos of different length. All longer than 1 minute.

**Comment by boredom2** [comment]
Hi @stigi - Malte is sadly sick this Week, thats why he didnt answer yet.
But most likely, he will return on Monday - and he will come back to you then.

**Comment by mfentross** [comment]
Hi @stigi ,

sorry, the documentation about this function was wrong. "swapToPos" swaps to a position within a playlist or itemlist. However I included a fix if the swapToPos parameter is out of bounds of the playlist. From v.3.2.21 we have the method seekToPos which does the seeking to a specific time in the current media.
