### ISSUE TITLE
Version 3.2.25 crashes the App when the App is put in background

### ISSUE THREAD

**Issue by ebonhart** [nexxtv/nexxPLAY-android#23]
The sdk version 3.2.25 crashes the App when the App is put in background while the player is active. It doesn't matter whether the App is put back in background manually or by clicking a preroll ad link. It doesn't matter whether the App is put in background during the preroll ad or during the productive video.

I mostly get these error messages, depening on device/situation:

`java.lang.NullPointerException: Attempt to invoke virtual method 'tv.dailyme.android.api.Video tv.nexx.android.player.Media.getDailyMeVideo()' on a null object reference
        at tv.nexx.android.player.ExoPlayerAdapter.getRendererBuilder(ExoPlayerAdapter.java:313)
        at tv.nexx.android.player.ExoPlayerAdapter.preparePlayer(ExoPlayerAdapter.java:272)
        at tv.nexx.android.player.ExoPlayerAdapter.prepare(ExoPlayerAdapter.java:510)
        at tv.nexx.android.player.logic.PlayerLogicStateMachine.imaVideoAdEnded(PlayerLogicStateMachine.java:2082)
        at tv.nexx.android.player.logic.IMAManager.onAdEvent(IMAManager.java:151)
        at com.google.obf.ir.a(IMASDK:65)
        at com.google.obf.ir.a(IMASDK:61)
        at com.google.obf.ir.a(IMASDK:98)
        at com.google.obf.ij.a(IMASDK:60)
        at com.google.obf.jd.f(IMASDK:180)
        at com.google.obf.jd.a(IMASDK:44)
        at com.google.obf.je.b(IMASDK:39)
        at com.google.obf.je$1.shouldOverrideUrlLoading(IMASDK:4)
        at android.webkit.WebViewClient.shouldOverrideUrlLoading(WebViewClient.java:73)
        at yk.b(PG:89)
        at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(PG:172)
        at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
        at org.chromium.base.SystemMessageHandler.handleMessage(PG:9)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)`

`java.lang.NullPointerException
        at tv.nexx.android.player.ExoPlayerAdapter.onPlayerStateChanged(ExoPlayerAdapter.java:398)
        at com.google.android.exoplayer2.ExoPlayerImpl.setPlayWhenReady(ExoPlayerImpl.java:198)
        at com.google.android.exoplayer2.SimpleExoPlayer.setPlayWhenReady(SimpleExoPlayer.java:693)
        at tv.nexx.android.player.ExoPlayerAdapter$Adapter.pause(ExoPlayerAdapter.java:786)
        at tv.nexx.android.player.control.VideoControllerView.doPauseResume(VideoControllerView.java:1273)
        at tv.nexx.android.player.control.VideoControllerView.access$1900(VideoControllerView.java:82)
        at tv.nexx.android.player.control.VideoControllerView$12.onClick(VideoControllerView.java:1204)
        at tv.nexx.android.player.control.VideoControllerView$3.onClick(VideoControllerView.java:660)
        at android.view.View.performClick(View.java:4084)
        at android.view.View$PerformClick.run(View.java:16966)
        at android.os.Handler.handleCallback(Handler.java:615)
        at android.os.Handler.dispatchMessage(Handler.java:92)
        at android.os.Looper.loop(Looper.java:137)
        at android.app.ActivityThread.main(ActivityThread.java:4745)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:511)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
        at dalvik.system.NativeStart.main(Native Method)`

**Observed on Android 8.0, 4.4, 4.1**

**Comment by mfentross** [comment]
Hi @ebonhart ,

thank you for reporting. This issue has been fixed in v3.2.27.
