### ISSUE TITLE
Version 3.2.27 crashes the App when the App is put in background 

### ISSUE THREAD

**Issue by ebonhart** [nexxtv/nexxPLAY-android#24]
The issue where putting the App into background leads to a Nexx Player crash is not fixed in version 3.2.27

Steps to reproduce:
1: Start a video
2: Wait until the preroll is over
3: During the actual video, put the App into the background
4: Bring the App into the Foreground again
5: The Nexx Player shows a black screen with the video controls on top of it.
6: Press the pause button

The App crashes with:

`    java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.exoplayer2.SimpleExoPlayer.seekTo(long)' on a null object reference
        at tv.nexx.android.player.ExoPlayerAdapter.onPlayerStateChanged(ExoPlayerAdapter.java:398)
        at com.google.android.exoplayer2.ExoPlayerImpl.setPlayWhenReady(ExoPlayerImpl.java:198)
        at com.google.android.exoplayer2.SimpleExoPlayer.setPlayWhenReady(SimpleExoPlayer.java:693)
        at tv.nexx.android.player.ExoPlayerAdapter$Adapter.pause(ExoPlayerAdapter.java:786)
        at tv.nexx.android.player.control.VideoControllerView.doPauseResume(VideoControllerView.java:1273)
        at tv.nexx.android.player.control.VideoControllerView.access$1900(VideoControllerView.java:82)
        at tv.nexx.android.player.control.VideoControllerView$12.onClick(VideoControllerView.java:1204)
        at tv.nexx.android.player.control.VideoControllerView$2.onClick(VideoControllerView.java:576)
        at android.view.View.performClick(View.java:6897)
        at android.view.View$PerformClick.run(View.java:26101)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)`

**Comment by mfentross** [comment]
Hi @ebonhart ,

sorry for the inconvenience. I was able to fix this in 3.2.28
