### ISSUE TITLE
NullPointerException crash in demo app

### ISSUE THREAD

**Issue by akonior** [nexxtv/nexxPLAY-android#4]
There is a NullPointerException crash in demo app just after video stream is open:

```
2018-07-31 12:42:01.155 4845-4845/com.nexxplaysample E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.nexxplaysample, PID: 4845
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
        at tv.nexx.android.player.reporting2.ReportingManager2._setContextVariables(ReportingManager2.java:166)
        at tv.nexx.android.player.reporting2.ReportingManager2._setReportingTemplate(ReportingManager2.java:116)
        at tv.nexx.android.player.reporting2.ReportingManager2.prepareTemplate(ReportingManager2.java:100)
        at tv.nexx.android.player.reporting2.ReportingManager2.mediaValidated(ReportingManager2.java:216)
        at tv.nexx.android.player.logic.PlayerLogicStateMachine.reportMediaValidated(PlayerLogicStateMachine.java:1551)
        at tv.nexx.android.player.logic.PlayerLogic.processMediaData(PlayerLogic.java:327)
        at tv.nexx.android.player.logic.PlayerLogic.access$200(PlayerLogic.java:29)
        at tv.nexx.android.player.logic.PlayerLogic$2.onMediaDataAvailable(PlayerLogic.java:302)
        at tv.nexx.android.player.logic.MediaManager$1.run(MediaManager.java:96)
        at tv.nexx.android.player.TransactionGetMedia$1.onSuccess(TransactionGetMedia.java:292)
        at tv.nexx.android.player.apiv3.APIManager$6$1.run(APIManager.java:421)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

**Comment by mfentross** [comment]
@akonior Thank you for reporting! This will be fixed in the next release.

**Comment by mfentross** [comment]
Fixed in v.3.0.0

**Comment by stigi** [comment]
Just had a similar exception in version `3.0.2`.

```
AndroidRuntime	FATAL EXCEPTION: main
Process: net.funk.tv, PID: 28026
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
	at tv.nexx.android.player.logic.PlayerLogicStateMachine.onTick(PlayerLogicStateMachine.java:1668)
	at tv.nexx.android.player.logic.PlayerLogic.onTick(PlayerLogic.java:281)
	at tv.nexx.android.player.logic.PlayerLogic$MessageHandler.handleMessage(PlayerLogic.java:591)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6541)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

Please reopen.
