### ISSUE TITLE
D8: Program type already present: android.support.v13.view.DragAndDropPermissionsCompat

### ISSUE THREAD

**Issue by stigi** [nexxtv/nexxPLAY-android#5]
Hi,

I am just trying to update to the latest version of the library that is distributed via maven.
When building our app with gradle, we get the error from $title.

Here's a bit of a longer excerpt:
```
> Task :app:transformDexArchiveWithDexMergerForDebug FAILED
D8: Program type already present: android.support.v13.view.DragAndDropPermissionsCompat
java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/107, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/0.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/1.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/2.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/3.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/4.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/5.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/6.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/8.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/9.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/10.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/11.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/12.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/13.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/14.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/15.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/16.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/17.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/18.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/19.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/20.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/21.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/22.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/23.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/24.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/25.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/26.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/27.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/28.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/29.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/30.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/31.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/32.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/33.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/34.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/35.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/36.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/37.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/38.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/39.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/40.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/41.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/42.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/43.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/44.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/45.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/46.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/47.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/48.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/49.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/50.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/51.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/52.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/53.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/54.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/55.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/56.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/57.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/58.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/59.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/60.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/61.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/62.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/63.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/64.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/65.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/66.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/67.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/68.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/69.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/70.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/71.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/72.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/73.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/74.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/75.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/76.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/77.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/78.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/79.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/80.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/81.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/82.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/83.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/84.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/85.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/87.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/88.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/89.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/90.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/91.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/92.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/93.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/94.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/95.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/96.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/97.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/98.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/99.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/100.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/101.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/102.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/104.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/105.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/106.jar, /Users/ullrich/Projects/funk-tv/android/app/build/intermediates/transforms/dexBuilder/debug/113.jar
        at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1431)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinTask.externalAwaitDone(ForkJoinTask.java:326)
        at java.util.concurrent.ForkJoinTask.doJoin(ForkJoinTask.java:391)
        at java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:719)
        at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:397)
        at com.android.build.gradle.internal.transforms.DexMergerTransform.transform(DexMergerTransform.java:221)
        at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:221)
        at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:217)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:102)
        at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:212)
        at sun.reflect.GeneratedMethodAccessor432.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
....
```

I used `gradlew app:dependencies` and saw that in v3 of the lib added a dependency on `com.android.support:support-v13:27.0.0`.
<details><summary>Details</summary>

```
+--- tv.nexx:nexxplay-android:3.+ -> 3.0.2
|    +--- com.google.android.instantapps:instantapps:1.1.0
|    +--- tv.nexx:android-offline-sdk:1.0.0
|    +--- com.google.android.exoplayer:exoplayer:2.8.1
|    |    +--- com.google.android.exoplayer:exoplayer-core:2.8.1
|    |    |    \--- com.android.support:support-annotations:27.0.0 -> 27.1.1
|    |    +--- com.google.android.exoplayer:exoplayer-dash:2.8.1
|    |    |    +--- com.google.android.exoplayer:exoplayer-core:2.8.1 (*)
|    |    |    \--- com.android.support:support-annotations:27.0.0 -> 27.1.1
|    |    +--- com.google.android.exoplayer:exoplayer-hls:2.8.1
|    |    |    +--- com.android.support:support-annotations:27.0.0 -> 27.1.1
|    |    |    \--- com.google.android.exoplayer:exoplayer-core:2.8.1 (*)
|    |    +--- com.google.android.exoplayer:exoplayer-smoothstreaming:2.8.1
|    |    |    +--- com.google.android.exoplayer:exoplayer-core:2.8.1 (*)
|    |    |    \--- com.android.support:support-annotations:27.0.0 -> 27.1.1
|    |    \--- com.google.android.exoplayer:exoplayer-ui:2.8.1
|    |         +--- com.google.android.exoplayer:exoplayer-core:2.8.1 (*)
|    |         +--- com.android.support:support-media-compat:27.0.0 -> 27.1.1 (*)
|    |         \--- com.android.support:support-annotations:27.0.0 -> 27.1.1
|    +--- com.google.android.exoplayer:extension-mediasession:2.8.1
|    |    +--- com.google.android.exoplayer:exoplayer-core:2.8.1 (*)
|    |    \--- com.android.support:support-media-compat:27.0.0 -> 27.1.1 (*)
|    +--- com.google.android.exoplayer:extension-leanback:2.8.1
|    |    +--- com.google.android.exoplayer:exoplayer-core:2.8.1 (*)
|    |    \--- com.android.support:leanback-v17:27.0.0 -> 27.1.1 (*)
|    +--- com.android.support:support-v13:27.0.0
|    |    +--- com.android.support:support-annotations:27.0.0 -> 27.1.1
|    |    \--- com.android.support:support-v4:27.0.0 -> 27.1.1 (*)
|    +--- com.android.support:leanback-v17:27.0.0 -> 27.1.1 (*)
|    +--- com.android.support:appcompat-v7:27.0.2 (*)
|    +--- com.google.code.gson:gson:2.8.0
|    +--- com.android.support:support-v4:27.0.2 -> 27.1.1 (*)
|    +--- org.springframework.android:spring-android-rest-template:2.0.0.M1
|    |    \--- org.springframework.android:spring-android-core:2.0.0.M1
|    +--- com.github.ybq:Android-SpinKit:1.0.5
|    +--- org.simpleframework:simple-xml:2.7.1
|    |    \--- stax:stax:1.2.0
|    +--- com.noveogroup.android:android-logger:1.3.1
|    |    \--- org.slf4j:slf4j-api:1.7.3 -> 1.7.7
|    +--- org.apache.mina:mina-statemachine:2.0.9
|    |    +--- commons-lang:commons-lang:2.6
|    |    \--- org.slf4j:slf4j-api:1.7.7
|    +--- com.google.ads.interactivemedia.v3:interactivemedia:3.7.4
|    \--- com.google.android.gms:play-services-ads:15.0.1
|         +--- com.android.support:customtabs:26.1.0
|         |    +--- com.android.support:support-compat:26.1.0 -> 27.1.1 (*)
|         |    \--- com.android.support:support-annotations:26.1.0 -> 27.1.1
|         +--- com.google.android.gms:play-services-ads-base:[15.0.1] -> 15.0.1
|         +--- com.google.android.gms:play-services-ads-identifier:[15.0.1,16.0.0) -> 15.0.1
|         |    \--- com.google.android.gms:play-services-basement:[15.0.1,16.0.0) -> 15.0.1
|         |         \--- com.android.support:support-v4:26.1.0 -> 27.1.1 (*)
|         +--- com.google.android.gms:play-services-ads-lite:[15.0.1] -> 15.0.1
|         |    +--- com.google.android.gms:play-services-ads-base:[15.0.1] -> 15.0.1
|         |    \--- com.google.android.gms:play-services-basement:[15.0.1,16.0.0) -> 15.0.1 (*)
|         +--- com.google.android.gms:play-services-basement:[15.0.1,16.0.0) -> 15.0.1 (*)
|         \--- com.google.android.gms:play-services-gass:[15.0.1] -> 15.0.1
|              +--- com.google.android.gms:play-services-ads-base:[15.0.1] -> 15.0.1
|              \--- com.google.android.gms:play-services-basement:[15.0.1,16.0.0) -> 15.0.1 (*)
```
</details>

I'm not sure where the clash during design happens, but are you by chance using a fixed version of support-v13 instead of something like `27.+`?

For now I work around the build issue the following exclude, but I'm sure this is quite the hack:

`
dependencies {
    configurations {
        all*.exclude group: 'com.android.support', module: 'support-v13'
    }
...
`

**Comment by mfentross** [comment]
Hi,

thank you for posting this. We need fixed versions to prevent incompatibilities. However I just uploaded v 3.1.1 of the SDK with the most recent versions of the dependencies.

**Comment by stigi** [comment]
I can confirm. The issue seem to be resolved now that `com.android.support:support-v13:27.1.1` matches our other support libs like `com.android.support:support-v4:27.1.1`.
