### ISSUE TITLE
NPE in PlayerLogicStateMachine.onTick()

### ISSUE THREAD

**Issue by stigi** [nexxtv/nexxPLAY-android#6]
I constantly am confronted with a NullPointerException inside `PlayerLogicStateMachine.onTick`:

```
AndroidRuntime	FATAL EXCEPTION: main
Process: [redacted], PID: 7016
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
	at tv.nexx.android.player.logic.PlayerLogicStateMachine.onTick(PlayerLogicStateMachine.java:1667)
	at tv.nexx.android.player.logic.PlayerLogic.onTick(PlayerLogic.java:281)
	at tv.nexx.android.player.logic.PlayerLogic$MessageHandler.handleMessage(PlayerLogic.java:591)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6119)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

From looking at the decompiled class in AndroidStudio it seems to be caused by this equality check `this.adManager.getAdType().equals("vast")` when `getAdType` returns null.

**Comment by stigi** [comment]
A workaround is overriding the ad type like so:

```
nexxPlayer.overrideAdType("vast")
```
